# Generated by Django 5.2.8 on 2025-11-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='studentcourse',
            table='student_course',
        ),
    ]
